"""initial_postgresql_schema

Revision ID: 94f0719a8d8f
Revises: 
Create Date: 2026-09-20 18:23:53.022306
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '94f0719a8d8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('icp_config', sa.JSON(), nullable=False),
    sa.Column('target_geography', sa.String(), nullable=False),
    sa.Column('target_industries', sa.JSON(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('company_size', sa.JSON(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('active_channels', sa.JSON(), nullable=False),
    sa.Column('daily_outreach_limit', sa.Integer(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('demo_mode', sa.Boolean(), nullable=False),
    sa.Column('demo_recipient_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('access_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('max_active_leads', sa.Integer(), nullable=False),
    sa.Column('specialties', sa.JSON(), nullable=False),
    sa.Column('regions', sa.JSON(), nullable=False),
    sa.Column('supported_channels', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('campaign_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('representative_id', sa.String(), nullable=False),
    sa.Column('assigned_by_id', sa.String(), nullable=False),
    sa.Column('daily_send_limit', sa.Integer(), nullable=True),
    sa.Column('assigned_lead_limit', sa.Integer(), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.Column('routing_rule', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_channel_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('working_hours', sa.JSON(), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_setups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('revenue_range', sa.JSON(), nullable=False),
    sa.Column('funding_stage', sa.JSON(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('exclusion_criteria', sa.JSON(), nullable=False),
    sa.Column('reference_profiles', sa.JSON(), nullable=False),
    sa.Column('custom_criteria', sa.JSON(), nullable=False),
    sa.Column('representative_settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('channel_configurations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospect_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('prospect_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('lifecycle_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=True),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('prompt_version_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_agent_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_agent_id', sa.String(), nullable=False),
    sa.Column('responsibilities', sa.JSON(), nullable=False),
    sa.Column('decision_thresholds', sa.JSON(), nullable=False),
    sa.Column('escalation_rules', sa.JSON(), nullable=False),
    sa.Column('prompt_version_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_agent_id'], ['campaign_agents.id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_agent_id')
    )
    op.create_table('campaign_prospects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('qualification_status', sa.String(), nullable=False),
    sa.Column('qualification_score', sa.Float(), nullable=False),
    sa.Column('qualification_reason', sa.Text(), nullable=False),
    sa.Column('current_stage', sa.String(), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(), nullable=True),
    sa.Column('campaign_specific_context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('blocked_reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_facts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppression_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('campaign_prospect_id', sa.String(), nullable=True),
    sa.Column('representative_id', sa.String(), nullable=True),
    sa.Column('request_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by_id', sa.String(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['campaign_prospect_id'], ['campaign_prospects.id'], ),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_prospect_id', sa.String(), nullable=False),
    sa.Column('representative_id', sa.String(), nullable=False),
    sa.Column('assigned_by_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_prospect_id'], ['campaign_prospects.id'], ),
    sa.ForeignKeyConstraint(['representative_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_prospect_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospect_research',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('research_summary', sa.Text(), nullable=False),
    sa.Column('person_research', sa.JSON(), nullable=False),
    sa.Column('company_research', sa.JSON(), nullable=False),
    sa.Column('icp_evidence', sa.JSON(), nullable=False),
    sa.Column('business_context', sa.JSON(), nullable=False),
    sa.Column('personalization_signals', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('agent_run_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('approval_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('intended_recipient', sa.String(), nullable=False),
    sa.Column('actual_recipient', sa.String(), nullable=False),
    sa.Column('delivery_mode', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('policy_decision', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('prospect_fitments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=False),
    sa.Column('prospect_id', sa.String(), nullable=False),
    sa.Column('organization_fit_score', sa.Float(), nullable=False),
    sa.Column('organization_fit_status', sa.String(), nullable=False),
    sa.Column('organization_criteria', sa.JSON(), nullable=False),
    sa.Column('contact_fit_score', sa.Float(), nullable=False),
    sa.Column('contact_fit_status', sa.String(), nullable=False),
    sa.Column('contact_criteria', sa.JSON(), nullable=False),
    sa.Column('overall_fit_score', sa.Float(), nullable=False),
    sa.Column('overall_fit_status', sa.String(), nullable=False),
    sa.Column('recommended_next_stage', sa.String(), nullable=False),
    sa.Column('key_fit_signals', sa.JSON(), nullable=False),
    sa.Column('key_risk_factors', sa.JSON(), nullable=False),
    sa.Column('uncertainties', sa.JSON(), nullable=False),
    sa.Column('research_id', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.ForeignKeyConstraint(['research_id'], ['prospect_research.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prospect_fitments')
    op.drop_table('delivery_records')
    op.drop_table('prospect_research')
    op.drop_table('messages')
    op.drop_table('lead_assignments')
    op.drop_table('approval_requests')
    op.drop_table('agent_decisions')
    op.drop_table('suppression_entries')
    op.drop_table('scheduled_actions')
    op.drop_table('research_facts')
    op.drop_table('outreach_events')
    op.drop_table('conversations')
    op.drop_table('campaign_prospects')
    op.drop_table('campaign_agent_configs')
    op.drop_table('agent_runs')
    op.drop_table('prospects')
    op.drop_table('prospect_batches')
    op.drop_table('knowledge_chunks')
    op.drop_table('channel_configurations')
    op.drop_table('campaign_setups')
    op.drop_table('campaign_channel_settings')
    op.drop_table('campaign_assignments')
    op.drop_table('campaign_agents')
    op.drop_table('access_profiles')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('prompt_versions')
    op.drop_table('knowledge_documents')
    op.drop_table('companies')
    op.drop_table('campaigns')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
