import React, { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocation, useNavigate } from 'react-router-dom';
import { AlertTriangle, Check, MessageSquare, Send, Users } from 'lucide-react';
import { representativeApi } from '../../api/representative';
import { MetricCard } from '../../components/ui/MetricCard';
import { StatusBadge } from '../../components/ui/StatusBadge';

const rejectReasons = ['WRONG_PERSONA', 'IRRELEVANT_HOOK', 'WRONG_INFORMATION', 'DUPLICATE_ACCOUNT', 'OTHER'];

export const RepresentativeWorkspace: React.FC = () => {
  const location = useLocation(); const navigate = useNavigate(); const client = useQueryClient();
  const [editing, setEditing] = useState<string | null>(null); const [draft, setDraft] = useState('');
  const { data, isLoading, error } = useQuery({ queryKey: ['rep-workspace'], queryFn: representativeApi.workspace, refetchInterval: 15000 });
  const action = useMutation({ mutationFn: async ({ kind, id, value }: any) => kind === 'approve' ? representativeApi.approve(id) : kind === 'edit' ? representativeApi.editApprove(id, value) : representativeApi.reject(id, value), onSuccess: () => { setEditing(null); client.invalidateQueries({ queryKey: ['rep-workspace'] }); client.invalidateQueries({ queryKey: ['rep-approvals'] }); } });
  if (isLoading) return <div className="text-slate-400">Loading your workspace…</div>;
  if (error || !data) return <div className="text-rose-300">Unable to load your assigned workspace.</div>;
  const tab = location.pathname.includes('conversations') ? 'conversations' : location.pathname.includes('approvals') ? 'approvals' : 'queue';
  const { metrics } = data; const atCapacity = metrics.capacity_used >= metrics.capacity_limit;
  return <div className="space-y-6">
    <div><h1 className="text-2xl font-bold text-white">My Queue</h1><p className="text-sm text-slate-400">All assigned work at a glance.</p></div>
    {atCapacity && <div className="rounded-xl border border-rose-500/40 bg-rose-950/30 p-3 text-sm text-rose-200"><AlertTriangle className="inline w-4 h-4 mr-2" />Daily sending capacity reached: {metrics.capacity_used}/{metrics.capacity_limit} units.</div>}
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
      <MetricCard value={metrics.pending_approvals} label="Pending approvals" color="purple" /><MetricCard value={metrics.active_conversations} label="Active conversations" color="amber" /><MetricCard value={metrics.meetings_booked} label="Meetings booked" color="emerald" /><MetricCard value={`${metrics.capacity_used} / ${metrics.capacity_limit}`} label="Daily sending capacity" subtext={`${metrics.capacity_remaining} units remaining`} color={atCapacity ? 'rose' : 'default'} />
    </div>
    <div className="flex gap-2 border-b border-purple-500/10 pb-2">{[['queue','Overview'],['approvals','Approvals'],['conversations','Conversations']].map(([key,label]) => <button key={key} onClick={() => navigate(key === 'queue' ? '/rep' : `/rep/${key}`)} className={`px-3 py-2 rounded-lg text-xs font-semibold ${tab === key ? 'bg-purple-600 text-white' : 'text-slate-400 hover:bg-[#12152d]'}`}>{label}</button>)}</div>
    {tab === 'queue' && <><h2 className="font-semibold text-white">Assigned campaigns</h2><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{data.campaigns.map((item: any) => <div key={item.campaign.id} className={`rounded-xl border p-4 ${item.campaign.status === 'PAUSED' ? 'opacity-60 border-amber-500/30 bg-amber-950/10' : 'border-purple-500/20 bg-[#0d0f22]'}`}><div className="flex justify-between gap-2"><strong className="text-sm text-white">{item.campaign.name}</strong><StatusBadge status={item.campaign.status} /></div><p className="text-xs text-slate-400 mt-2">{item.campaign.target_roles?.join(', ') || 'Configured ICP'} · {item.campaign.target_industries?.join(', ') || 'All industries'}</p><p className="text-xs text-slate-300 mt-3">{item.channels.map((c:any) => `${c.channel} ${c.enabled ? 'LIVE' : 'PAUSED'}`).join(' · ')}</p><p className="text-xs text-purple-300 mt-2">{item.workload} assigned leads · {item.open_conversations} conversations still open{item.campaign.status === 'PAUSED' ? ' — Paused by Manager' : ''}</p></div>)}</div></>}
    {tab === 'approvals' && <div className="space-y-3">{data.approvals.map((item:any) => <div key={item.approval.id} className="rounded-xl border border-purple-500/15 bg-[#0d0f22] p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold text-white">{item.prospect.first_name} {item.prospect.last_name} <span className="text-slate-400 font-normal">· {item.campaign.name}</span></div><div className="text-xs text-slate-400 mt-1">{item.prospect.title} · {item.prospect.industry} · Fit {Math.round(item.association.qualification_score || 0)}</div></div><StatusBadge status={item.approval.payload?.priority || 'PENDING'} /></div><p className="text-sm text-slate-200 mt-3 whitespace-pre-line">{editing === item.approval.id ? <textarea className="w-full min-h-28 bg-[#070811] border border-purple-500/30 rounded p-2" value={draft} onChange={e=>setDraft(e.target.value)} /> : item.approval.payload?.message || item.approval.payload?.summary}</p><div className="flex flex-wrap gap-2 mt-3"><button disabled={atCapacity || action.isPending} onClick={()=>action.mutate({kind:'approve',id:item.approval.id})} className="px-3 py-1.5 text-xs rounded bg-emerald-700 text-white disabled:opacity-50"><Check className="inline w-3 h-3 mr-1" />Approve</button><button onClick={()=>{setEditing(item.approval.id);setDraft(item.approval.payload?.message || '')}} className="px-3 py-1.5 text-xs rounded bg-purple-700 text-white">Edit</button>{editing===item.approval.id && <button disabled={atCapacity} onClick={()=>action.mutate({kind:'edit',id:item.approval.id,value:draft})} className="px-3 py-1.5 text-xs rounded bg-purple-600 text-white">Edit & Approve</button>}<select onChange={e=>e.target.value && action.mutate({kind:'reject',id:item.approval.id,value:e.target.value})} defaultValue="" className="text-xs bg-[#070811] border border-rose-500/30 rounded px-2 text-rose-200"><option value="">Reject…</option>{rejectReasons.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></div></div>)}{!data.approvals.length && <p className="text-slate-400">No approvals waiting for you.</p>}</div>}
    {tab === 'conversations' && <div className="space-y-3">{data.conversations.map((item:any) => <div key={item.conversation.id} className="rounded-xl border border-purple-500/15 bg-[#0d0f22] p-4 flex justify-between"><div><div className="font-semibold text-white">{item.prospect.first_name} {item.prospect.last_name}</div><div className="text-xs text-slate-400 mt-1">{item.campaign.name} · {item.prospect.title}</div>{item.campaign.status === 'PAUSED' && <p className="text-xs text-amber-300 mt-2">Campaign paused — you can finish this conversation, but no new prospects will enter.</p>}</div><div className="flex items-center gap-2"><StatusBadge status={item.conversation.status} /><MessageSquare className="w-4 h-4 text-purple-300" /></div></div>)}{!data.conversations.length && <p className="text-slate-400">No assigned conversations.</p>}</div>}
  </div>;
};
